-- Student Civic Hub - Supabase schema
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists petition_signatures (
  id bigint generated by default as identity primary key,
  name text not null,
  department text,
  year text,
  message text,
  consent boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists issues (
  id bigint generated by default as identity primary key,
  ticket_id text unique not null,
  category text not null,
  title text not null,
  description text not null,
  department text,
  year text,
  name text,
  contact text,
  anonymous boolean not null default true,
  status text not null default 'Received',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public_updates (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists issue_status_requests (
  id bigint generated by default as identity primary key,
  ticket_id text,
  created_at timestamptz not null default now()
);

alter table petition_signatures enable row level security;
alter table issues enable row level security;
alter table public_updates enable row level security;
alter table issue_status_requests enable row level security;

-- Public users can INSERT petitions.
drop policy if exists petition_public_insert on petition_signatures;
create policy petition_public_insert
on petition_signatures for insert
to anon
with check (consent = true);

-- Public users can INSERT problem reports.
drop policy if exists issues_public_insert on issues;
create policy issues_public_insert
on issues for insert
to anon
with check (true);

-- Public users can read published updates.
drop policy if exists updates_public_read on public_updates;
create policy updates_public_read
on public_updates for select
to anon
using (true);

-- Public users may record a status lookup request.
drop policy if exists status_request_insert on issue_status_requests;
create policy status_request_insert
on issue_status_requests for insert
to anon
with check (true);

-- IMPORTANT:
-- Do NOT create public SELECT/UPDATE/DELETE policies for petition_signatures or issues.
-- The app uses the Supabase service-role key only on the server for admin operations.

-- Public issue-status lookup is intentionally handled through a safe view.
drop view if exists public_issue_status;
create view public_issue_status as
select ticket_id, status, updated_at
from issues;

grant select on public_issue_status to anon;

-- Optional: prevent anonymous users from directly selecting the base issue table.
revoke select on issues from anon;
revoke select on petition_signatures from anon;
